### ISSUE TITLE
make `yapf` a dependency?

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/jupyter_nbextensions_configurator-feedstock#10]
I'm always met with the "yapf not installed" error when using the code prettyfier. Should it maybe made a dependency for this package?

**Comment by jcb91** [comment]
mm, I suppose it could be. I'd hesitate to add it explicitly, but I guess the notebook runs on python anyway. Also, @jfbercher & I have recently been adapting code_prettify to be more configurable, so yapf isn't necessarily a dependency at all anymore for someone using a different formatter. Not sure, thoughts @juhasch, @jfbercher?

**Comment by jcb91** [comment]
ugh, whoops, thought this was on [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions). So, if we add yapf as a dependency, it'd be there, rather than here, as the configurator doesn't provide code_prettify at all.

**Comment by jcb91** [comment]
Closing this issue here, to re-open it as [jupyter_contrib_nbextensions#832](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/832)...
