### ISSUE TITLE
Problem destroying environment with the configurator insalled?

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/jupyter_nbextensions_configurator-feedstock#17]
Hey-lo,

I set up a conda environment the other day that included jupyter and the nbextensions_configurator. When I destroyed it today, I got this error at tear-down:
```bash
Unlinking packages ...
[      COMPLETE      ]|####################################################################################| 100%
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ddw/bin/jupyter-nbextension", line 4, in <module>
    import notebook.nbextensions
  File "/opt/anaconda3/envs/ddw/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/opt/anaconda3/envs/ddw/lib/python3.5/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named 'jupyter_core'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ddw/bin/jupyter-serverextension", line 4, in <module>
    import notebook.serverextensions
  File "/opt/anaconda3/envs/ddw/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/opt/anaconda3/envs/ddw/lib/python3.5/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named 'jupyter_core'
```

Then `ddw` environment is gone, so all seems well, but it's a little strange.

**Comment by jcb91** [comment]
Hi! Apologies, I've only just seen this issue. Hmm, that is strange. Perhaps `jupyter_core` needs to be required for build, as well as run?! Have you seen this more than once?

**Comment by pmlandwehr** [comment]
>  Have you seen this more than once?

No, but I also only create virtual environments on a rare basis.

**Comment by jakirkham** [comment]
Just to chime in here, this looks suspiciously like issue ( https://github.com/conda/conda/issues/5417 ). Namely `jupyter_nbextensions_configurator` should be uninstalled before `jupyter_core` is uninstalled. However `conda` does not remove packages based on the topological order. So instead one sees the uninstall of `jupyter_nbextensions_configurator` fails because `jupyter_core` was uninstalled first. Not much can be done about it here as there is no way to control the uninstall order currently.

**Comment by jakirkham** [comment]
cc-ing @kalefranz for awareness.

**Comment by jcb91** [comment]
Ah, ok, thanks for the info @jakirkham, that sounds like it makes sense as a cause here...

**Comment by ocefpaf** [comment]
Closing this as stale. @pmlandwehr please follow up on the conda issue upstream if you are still experiencing this.
